delete ACCESS_RESULT_DATA from ACCESS_RESULT_DATA
	inner join ACCESS_RESULT
	on ACCESS_RESULT_DATA.ID = ACCESS_RESULT.ID
/*BEGIN*/where 
	/*IF pmb != null*/ACCESS_RESULT.SESSION_ID = /*pmb*/'20090704161034370'/*END*/
/*END*/
